name: build and test

on:
  push:
    branches:
      - main
    tags:
      - v*

env:
  DOTNET_VERSION: '8.x' # The .NET SDK version to use

jobs:
  build-and-test:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: 'Get Version'
      id: version
      uses: battila7/get-version-action@v2

    - name: 'Print Version'
      run: echo ${{ steps.version.outputs.version-version-without-v }}